In [60]:
import numpy as np
import pandas as pd

In [61]:
header =["dep_1", "dep_2", "dep_3", "dep_4"]
materiel = ["Iron", "Copper", "Aluminum", ]
value = [[45200, 65190, 10000,33500],
         [16000, 11500, 8550, 73200],
         [13050, 15000, 22050, 8030]]
data = pd.DataFrame(value, columns=header, index= materiel)
print (data)

          dep_1  dep_2  dep_3  dep_4
Iron      45200  65190  10000  33500
Copper    16000  11500   8550  73200
Aluminum  13050  15000  22050   8030


header =["dep_1", "dep_2", "dep_3", "dep_4"]
value = [[45200, 65190, 10000,33500],
         [16000, 11500, 8550, 73200],
         [13050, 15000, 22050, 8030]]
materiel = ["Iron", "Copper", "Aluminum"]
footer = ["Product", "...", "...", "...", "..."]
data = {"head" : header,
        "materiel" : materiel,
        "value" : value,
        "footer" : footer
        }
print (data)

In [62]:
print (np.max(data, 0))
print (np.max(data, 1))
print (data.mean())
# print (data[:].values)


dep_1    45200
dep_2    65190
dep_3    22050
dep_4    73200
dtype: int64
Iron        65190
Copper      73200
Aluminum    22050
dtype: int64
dep_1    24750.000000
dep_2    30563.333333
dep_3    13533.333333
dep_4    38243.333333
dtype: float64


In [63]:
def Product( data:pd.DataFrame):
    value0 = data.iloc[:, 0].values, data.iloc[:, 1].values, data.iloc[:, 2].values, data.iloc[:, 3].values
    product, rest = [], []
    for i in value0:
        maxProduct0 = np.min(i[0]/10) ;maxProduct1 = np.min(i[1]/5); maxProduct2 = np.min(i[2]/6)
        maxProduct = np.min([maxProduct0, maxProduct1, maxProduct2])
        product.append(maxProduct)
    product = np.array(np.round(product))
    k=0
    for i in product:
        rest1 = value0[k][0];rest2 = value0[k][1];rest3 = value0[k][2]; 
        for j in range(int (i)):
            rest1 = rest1-10; rest2 = rest2-5; rest3 = rest3-6
            if rest1 == 0 or rest3 == 0 or rest2 == 0: rest.append([rest1, rest2, rest3]); break;
            elif rest1 < 9 or rest3 < 5 or rest2 < 4: rest.append([rest1, rest2, rest3]); break;
        k=k+1
    rest = np.array(rest);rest = np.transpose(rest)
    remining = [rest[0]*3, rest[1]*8, rest[2]*6]
    return product, rest, remining


In [64]:
pices, rest, remain = Product( data)
print(f"pices = \n{pices},\n"+
      f"rest = \n{rest},\n"+
      f"remining = \n{remain},\n"+
      f"sum remining = \n{sum(remain)},\n"+
      f"sum = {sum(sum(remain))}")


pices = 
[2175. 2300. 1000. 1338.],
rest = 
[[23450 42190     0 20120]
 [ 5125     0  3550 66510]
 [    0  1200 16050     2]],
remining = 
[array([ 70350, 126570,      0,  60360], dtype=int64), array([ 41000,      0,  28400, 532080], dtype=int64), array([    0,  7200, 96300,    12], dtype=int64)],
sum remining = 
[111350 133770 124700 592452],
sum = 962272
